// autogenerated by cmake

#ifndef _CONFIG_H_
#define _CONFIG_H_

#define KFREEFLIGHT_MAJOR @kfreeflight_MAJOR@
#define KFREEFLIGHT_MINOR @kfreeflight_MINOR@
#define KFREEFLIGHT_PATCH @kfreeflight_PATCH@
#define KFREEFLIGHT_VERSION "@kfreeflight_VERSION@"

#define KFREEFLIGHT_SOURCE_DIR "@kfreeflight_SOURCE_DIR@"

#define FG_ROOT "@WITH_FG_ROOT@"
#define FG_SCENERY "@WITH_FG_SCENERY@"

#cmakedefine WITH_OPENSCENEGRAPH_ENABLED

#endif // _CONFIG_H_